@echo off
cls

set DRIVE_LETTER=%1:
set GAME_PATH=%DRIVE_LETTER%/CSC4903

set OGRE_PATH=%GAME_PATH%/Ogre-1.8.1
set BOOST_PATH=%GAME_PATH%/boost_1_63_0
set FREEIMAGE_PATH=%GAME_PATH%/FreeImage-3.17.0_Win32Win64
set ZLIB_PATH=%GAME_PATH%/zlib-1.2.11
set TINYXML_PATH=%GAME_PATH%/tinyxml_2.6.2
set OIS_PATH=%GAME_PATH%/ois
set BASS_PATH=%GAME_PATH%/bass-2.4
set CE_PATH=%GAME_PATH%/cegui-0.8.7
set LUA_PATH=%GAME_PATH%/lua-5.3.4
set BULLET_PATH=%GAME_PATH%/bullet3-2.85.1

set TDM=%DRIVE_LETTER%/TDM-GCC-64

set PATH=%TDM%/bin;%LUA_PATH%/lib;%CE_PATH%/dependencies/bin;%CE_PATH%/build/bin;%BASS_PATH%;%OIS_PATH%/lib;%OGRE_PATH%/build/bin;%BOOST_PATH%/stage/lib;%ZLIB_PATH%/lib;%FREEIMAGE_PATH%/lib;c:/windows
mingw32-make BULLET_PATH=%BULLET_PATH% LUA_PATH=%LUA_PATH% CE_PATH=%CE_PATH%/build BASS_PATH=%BASS_PATH% OIS_PATH=%OIS_PATH% OGRE_PATH=%OGRE_PATH% BOOST_PATH=%BOOST_PATH% GAME_PATH=%GAME_PATH% TINYXML_PATH=%TINYXML_PATH%